DOMAIN = "peaqnext"
PLATFORMS = ["sensor"]
HUB = "hub"

CONF_SENSORS = "sensors"
CONF_CONSUMPTION_TYPE = "consumption_type"
CONF_NAME = "name"
CONF_TOTAL_DURATION_IN_MINUTES = "total_duration_in_minutes"
CONF_TOTAL_CONSUMPTION_IN_KWH = "total_consumption_in_kwh"
CONF_NONHOURS_START = "non_hours_start"
CONF_NONHOURS_END = "non_hours_end"
CONF_CLOSEST_CHEAP = "closest_cheap_hour"
CONF_CUSTOM_CONSUMPTION_PATTERN = "custom_consumption_pattern"
CONF_DEDUCT_PRICE = "deduct_price"
CONF_UPDATE_BY = "update_by"
CONF_CALCULATE_BY = "calculate_by"
