override_sensor_data:
  name: Override Sensor Data
  description: bla bla bla
  fields:
    sensor_entity:
      description: >
        Bla bla bla
      example: 'sensor.peaqnext_washer' or 'peaqnext_washer' or 'washer'
    duration_in_minutes:
      description: >
        bla bla bla
      example: 60
    consumption_in_kwh:
      description: >
        bla bla bla
      example: 0.5
    custom_consumption_pattern:
      description: >
        bla bla bla
      example: 1, 1.1, 2, 0
    non_hours_start:
      description: >
        bla bla bla
      example: [22, 23]
    non_hours_end:
      description: >
        bla bla bla
      example: [6, 7]
    timeout:
      description: >
        bla bla bla
      example: 8 or "2023-01-01 03:00:00"