name: Validate with HACS

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  
jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
