name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: ZIP peaqev Dir
        run: |
          cd ${{ github.workspace }}/custom_components/peaqev
          zip peaqev.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/peaqev/peaqev.zip
          asset_name: peaqev.zip
          tag: ${{ github.ref }}
          overwrite: true